# Generated by Django 4.2.6 on 2023-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(default='', max_length=250)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default='')),
                ('updated_at', models.DateTimeField(default='')),
            ],
        ),
    ]
