# Generated by Django 4.2.6 on 2023-10-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_myblogpost_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblogpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='myblogpost',
            name='updated_at',
        ),
    ]
